import Link from "next/link";
import { ArrowLeft, FileText } from "lucide-react";
import { Button } from "@/components/shadcn-ui/button";
import { SITE_NAME, SITE_URL } from "@/lib/siteConfig";

export const metadata = {
  title: `Terms of Service · ${SITE_NAME}`,
  description: `Terms of service for ${SITE_NAME} — acceptable use, disclaimers, and user responsibilities.`,
};

export default function TermsPage() {
  return (
    <main className="min-h-screen px-4 py-12 sm:px-8 md:px-10 slg:px-16 lg:px-24 max-w-[860px] mx-auto">
      {/* Back nav */}
      <Button asChild variant="ghost" size="sm" className="mb-8 gap-1.5 text-muted-foreground hover:text-foreground -ml-2">
        <Link href="/">
          <ArrowLeft className="w-3.5 h-3.5" />
          Back to BioLoom
        </Link>
      </Button>

      {/* Header */}
      <div className="flex items-center gap-3 mb-2">
        <div className="w-10 h-10 rounded-xl bg-primary/10 border border-primary/20 flex items-center justify-center shrink-0">
          <FileText className="w-5 h-5 text-primary" />
        </div>
        <h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1>
      </div>
      <p className="text-sm text-muted-foreground mb-10">
        Last updated: May 5, 2025 &nbsp;·&nbsp; Effective immediately
      </p>

      <div className="prose prose-sm dark:prose-invert max-w-none space-y-8 text-foreground/90 leading-relaxed">

        <section>
          <h2 className="text-lg font-semibold mb-3">1. Acceptance of Terms</h2>
          <p>
            By accessing or using {SITE_NAME} at{" "}
            <a href={SITE_URL} className="text-primary underline underline-offset-4">{SITE_URL}</a>,
            you agree to be bound by these Terms of Service. If you do not agree to these terms,
            please do not use the service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">2. Description of Service</h2>
          <p>
            {SITE_NAME} is a free, open-source web application that uses AI language models to
            generate professional bio suggestions. The service is provided &quot;as is&quot; without
            any warranty of uptime, accuracy, or suitability for a particular purpose.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">3. Acceptable Use</h2>
          <p>You agree to use {SITE_NAME} only for lawful purposes. You must not:</p>
          <ul className="list-disc pl-5 mt-2 space-y-1.5">
            <li>Use the service to generate content that is defamatory, harassing, or illegal</li>
            <li>Attempt to circumvent rate limits, access controls, or API keys</li>
            <li>Use automated tools to scrape or bulk-generate content in a way that
              degrades service quality for other users</li>
            <li>Misrepresent AI-generated bios as independently written for deceptive purposes</li>
            <li>Use the service to generate content that impersonates real individuals without consent</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">4. Intellectual Property</h2>
          <p>
            The {SITE_NAME} source code is licensed under the{" "}
            <a
              href="https://github.com/zhenxiao-yu/ai-bio-generator/blob/main/LICENSE"
              className="text-primary underline underline-offset-4"
              target="_blank"
              rel="noopener noreferrer"
            >
              MIT License
            </a>
            . You are free to fork, modify, and deploy your own version under the terms of that license.
          </p>
          <p className="mt-3">
            Bios generated through the service are produced by third-party AI models. You own the
            content you create and are responsible for how you use it. We make no claim of
            copyright over generated bio text.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">5. AI-Generated Content Disclaimer</h2>
          <p>
            Bios are generated by AI language models and may contain inaccuracies, biases, or
            content that does not accurately represent you. You are solely responsible for
            reviewing, editing, and verifying any bio before publishing it publicly. {SITE_NAME}
            does not guarantee the accuracy, completeness, or suitability of generated content.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">6. Third-Party Services</h2>
          <p>
            {SITE_NAME} forwards your input to third-party AI providers (Groq, Google Gemini) to
            generate responses. Your use of {SITE_NAME} is also subject to the terms of these
            providers. We are not responsible for the availability, accuracy, or conduct of
            third-party services.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">7. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by applicable law, {SITE_NAME} and its contributors
            shall not be liable for any indirect, incidental, special, consequential, or punitive
            damages, including but not limited to loss of profits, data, goodwill, or other
            intangible losses, resulting from your use of or inability to use the service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">8. Warranty Disclaimer</h2>
          <p>
            {SITE_NAME} is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind,
            express or implied, including but not limited to warranties of merchantability,
            fitness for a particular purpose, and non-infringement. We do not warrant that
            the service will be uninterrupted, error-free, or free of harmful components.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">9. Service Availability</h2>
          <p>
            {SITE_NAME} is a free, volunteer-maintained project. We reserve the right to modify,
            suspend, or discontinue the service at any time without notice. We are not liable
            for any interruption or cessation of service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">10. Governing Law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with the laws of the
            jurisdiction in which the service operator resides, without regard to its conflict of
            law provisions.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">11. Changes to Terms</h2>
          <p>
            We reserve the right to update these Terms at any time. The &quot;Last updated&quot; date
            at the top of this page will reflect changes. Continued use of {SITE_NAME} after
            changes are posted constitutes your acceptance of the revised Terms.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-3">12. Contact</h2>
          <p>
            Questions about these Terms? Open an issue on our{" "}
            <a
              href="https://github.com/zhenxiao-yu/ai-bio-generator/issues"
              className="text-primary underline underline-offset-4"
              target="_blank"
              rel="noopener noreferrer"
            >
              GitHub repository
            </a>
            .
          </p>
        </section>

      </div>

      <div className="mt-12 pt-6 border-t border-border flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <p className="text-xs text-muted-foreground">
          {SITE_NAME} is open-source under the MIT License.
        </p>
        <div className="flex gap-3 text-xs text-muted-foreground">
          <Link href="/privacy" className="hover:text-foreground transition-colors">Privacy Policy</Link>
          <span>·</span>
          <Link href="/about" className="hover:text-foreground transition-colors">About</Link>
        </div>
      </div>
    </main>
  );
}
